<?php
/**
 * @file
 * views_aggregator.module
 *
 * Module implementig post-query aggregation functions for Views tables.
 */

require_once 'views/views_aggregator_functions.inc';
//require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'views_aggregator') . 'views/views_aggregator_functions.inc';

/**
 * Implements hook_help().
 */
function views_aggregator_help($path, $arg) {
  switch ($path) {
    case 'admin/help#views_aggregator':
      return t('See the <a href="@README">README</a> for View configuration instructions and examples or browse the <a href="@project">project</a> support queue.', array(
        '@project' => url('http://drupal.org/project/views_aggregator'),
        '@README' => url(drupal_get_path('module', 'views_aggregator') . '/README.txt'),
      ));
  }
}

/**
 * Implements hook_theme().
 */
function views_aggregator_theme() {
  $base_path = drupal_get_path('module', 'views_aggregator');
  $themes = array(
    'views_aggregator_plugin_style_table' => array(
      // Pass $form to theme_views_aggregator_plugin_style_table($vars)
      'render element' => 'form',
      'path' =>  $base_path . '/views',
      'file' => 'theme_views_aggregator_plugin_style_table.inc',
    ),
  );
  return $themes;
}

/**
 * Implements hook_views_api().
 */
function views_aggregator_views_api() {
  return array(
    'api' => views_api_version(),
    'path' => drupal_get_path('module', 'views_aggregator') . '/views',
  );
}

/**
 * Get all avaialble aggregation function definitions.
 *
 * @param string name
 *   The name of the desired function or NULL to retrieve an array of functions.
 *
 * @return array
 *   An array of aggregation function parameters.
 */
function views_aggregator_get_aggregation_functions_info($name = NULL) {

  $aggregation_functions = &drupal_static(__FUNCTION__);

  if (empty($aggregation_functions)) {
    // Collect aggregations functions defined in other modules via their
    // hook_views_aggregation_functions_info() implementations.
    $aggregation_functions = module_invoke_all('views_aggregation_functions_info');

    // Let other modules alter the aggregation functions by implementing
    // hook_views_aggregation_functions_alter().
    drupal_alter('views_aggregation_functions_info', $aggregation_functions);
  }
  //$aggregation_functions = (array)$aggregation_functions;
  if (empty($name)) {
    return $aggregation_functions;
  }
  if (isset($aggregation_functions[$name])) {
    return $aggregation_functions[$name];
  }
}

/**
 * Returns the result value at the intersection of column and row.
 *
 * @param object $field_handler
 *   The handler associated with the table column being requested.
 *
 * @param object $result_row
 *   The result row object
 *
 * @return mixed
 */
function views_aggregator_get_cell($field_handler, $result_row) {
  $value = $field_handler->get_value($result_row);
  if (!isset($value)) {
    // This may happen with a $field_handler like views_php_handler_field that
    // doesn't have its value available until after rendering. Render it here.
    $value = $field_handler->render($result_row);
  }
  // The following is somewhat heuristic -- @todo
  if (is_array($value)) {
    $value = reset($value);
    if (is_array($value)) {
      $value = reset($value);
    }
  }
  return $value;
}

/**
 * Sets a value on the cell identified by the supplied column and row.
 *
 * @param object $field_handler
 *   The handler associated with the table column being requested.
 * @param object $result_row
 *   The result row object.
 * @param int $row_num
 *   The result row number. Required for fields, not for properties or PHP.
 * @param mixed $simple_value
 *   The raw (not marked-up) value to set, a number or string.
 */
function views_aggregator_set_cell($field_handler, &$result_row, $row_num, $simple_value) {
  $field_name = $field_handler->options['id'];
  $field_alias = $field_handler->field_alias;

  // See if we're dealing with a field, as opposed to views_handler_field_node.
  if (is_a($field_handler, 'views_handler_field_field')) {
    // The new value needs to be set in two places. First in _field_data[]...
    // All of the foreach's below loop only once...
    $languages = $result_row->_field_data[$field_alias]['entity']->{$field_name};
    foreach ($languages as $lang => $item) {
      foreach ($item as $i => $values) {
        foreach ($values as $name => $value) {
          // Most fields: $name == 'value'
          // Taxonomy term: $name == 'tid'
          if ($name == 'tid' && !is_numeric($simple_value)) {
            drupal_set_message(t('Views Aggregator Plus: cannot change taxonomy term %field from %value to non-numeric value "%new-value".', array(
              '%field' => $field_name, '%value' => $value, '%new-value' => $simple_value,
            )), 'warning');
          }
          $result_row->_field_data[$field_alias]['entity']->{$field_name}[$lang][$i][$name] = $simple_value;
          break;
        }
        break;
      }
    }
    // Next employ set_items() to re-render the _field_data[] updated above.
    // Place both the 'raw' and 'rendered' versions in field_...[].
    $result_row->{'field_' . $field_name} = $field_handler->set_items($result_row, $row_num);
    return;
  }
  if (is_a($field_handler, 'views_php_handler_field')) {
    // This prevents Views PHP from re-rendering the code snippet and makes it
    // pick up the value from $result_row, as set in the statement below.
    $field_handler->options['php_output'] = FALSE;
  }
  // PHP or plain node property, not a field. Example: 'node_title'.
  $result_row->{$field_alias} = $simple_value;
}

/**
 * Set a column of group values on the view.
 *
 * @param object $view
 *   the View object
 * @param object $field_handler
 *   the column handler
 * @param array $group_values
 *   the values to set, indexed by group
 */
function views_aggregator_set_column($view, $field_handler, $group_values) {
  foreach ($view->group as $group => $rows) {
    if ($group != 'column' && isset($group_values[$group])) {
      foreach ($rows as $num => $row) {
        views_aggregator_set_cell($field_handler, $row, $num, $group_values[$group]);
        // Only have to do the first row of the group.
        break;
      }
    }
  }
}

/**
 * Prepare to render the view results as a table style.
 *
 * The rendering to HTML happens in views-aggregator-results-table.tpl.php
 *
 * See also:
 * template_preprocess_views_view_table(&$vars) in Views
 */
function template_preprocess_views_aggregator_results_table(&$vars) {
  $view = &$vars['view'];

  if (!empty($view->group)) {
    unset($view->style_plugin->rendered_fields);
    $vars['rows'] = array();
    // Note: at this stage each group consist of one row, i.e. count($rows)==1.
    foreach ($view->group as $rows) {
      $vars['rows'][] = reset($rows);
    }
  }
  if (array_filter($view->totals) != array()) {
    $vars['footer'] = $view->totals;
  }
  unset($view->group);
  unset($view->totals);
  if (!isset($view->row_index)) {
    // Have seen trouble when this is not set...
    $view->row_index = '';
  }
  // Now render as per normal.
  template_preprocess_views_view_table($vars);
}
